sudo: false # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
language: node_js
node_js:
  - 6
  - 7

notifications:
  email:
    - medikoo+i18n2-md-to-dom@medikoo.com

script: "npm test && npm run lint"
